### ISSUE TITLE
When used with Hwyla, planting soybeans will collapse

### ISSUE THREAD

**Issue by pz775819662** [ProjectUranus/FoodCraft-Reloaded#8]
When used with Hwyla, planting soybeans will collapse

**Comment by RisingInIris2017** [comment]
I have the same issue.
What's worse, both Hwyla and The One Probe mod can trigger this issue. Simply looking at the crop, then game wil crash.

Crash report:
Hwyla: https://paste.ubuntu.com/p/869mm6S32C/
TOP: https://paste.ubuntu.com/p/sSzZJkyGCb/
